apiVersion: v1
kind: PersistentVolume
metadata:
  name: chromadb-pv
  labels:
    type: local
spec:
  storageClassName: nfs-csi
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"